CREATE DATABASE IF NOT EXISTS sociofuria;
USE sociofuria;

CREATE TABLE IF NOT EXISTS cadastro_pendentes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    telefone VARCHAR(20),
    cpf VARCHAR(14) UNIQUE NOT NULL,
    rg VARCHAR(20),
    data_nascimento DATE,
    sexo ENUM('M', 'F', 'Outro'),
    foto VARCHAR(255),
    nome_mae VARCHAR(255),
    nome_pai VARCHAR(255),
    cep VARCHAR(10),
    endereco VARCHAR(255),
    numero VARCHAR(10),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(2),
    estado_civil VARCHAR(50),
    escolaridade VARCHAR(100),
    profissao VARCHAR(100),
    comando VARCHAR(100),
    responsavel VARCHAR(255),
    cpf_responsavel VARCHAR(14),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS associados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero_socio VARCHAR(10) UNIQUE NOT NULL,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    telefone VARCHAR(20),
    cpf VARCHAR(14) UNIQUE NOT NULL,
    rg VARCHAR(20),
    data_nascimento DATE,
    sexo ENUM('M', 'F', 'Outro'),
    foto VARCHAR(255),
    nome_mae VARCHAR(255),
    nome_pai VARCHAR(255),
    cep VARCHAR(10),
    endereco VARCHAR(255),
    numero VARCHAR(10),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(2),
    estado_civil VARCHAR(50),
    escolaridade VARCHAR(100),
    profissao VARCHAR(100),
    comando VARCHAR(100),
    responsavel VARCHAR(255),
    cpf_responsavel VARCHAR(14),
    status ENUM('ativo', 'atrasado', 'inativo', 'suspenso') DEFAULT 'ativo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
